############################################################
#
# 网关zuul
#
############################################################
server:
  port: 7070
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: springcloud-eureka-zuul
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
  zipkin:
      # 配置zipkin采集的服务地址，数据会发送到这里
      base-url: http://192.168.93.129:9411/
      sender:
        # 数据采集的传输通信方式，web http的形式
        type: web
    sleuth:
      sampler:
        # 数据采样比例（百分数），0~1
        probability: 1


############################################################
#
# 配置zuul
#路由规则: http://[网关地址]:[端口号]/[prefix]/[微服务实例id]/[请求地址路径]
#
############################################################
zuul:
  routes:
    service-article: /service-article/**
    springcloud-eureka-zuul: /springcloud-eureka-zuul/**
#    article:
#      path: /article/**
#      url: http://192.168.2.221:8001
  prefix: /api


eureka:
  server:
    hostname: eureka
    port: 7000
  client:
    service-url:
#      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/
  instance:
      lease-renewal-interval-in-seconds: 3      # 调整微服务（eureka client）和注册中心（eureka server）的心跳时间
      lease-expiration-duration-in-seconds: 5   # eureka 举例最近的一次心跳等待提出的时间，默认90s

blackIp:
  limitTimes: 10

management:
  endpoints:
    web:
      exposure:
        include: refresh